//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetail
    {
        public int DetailID { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<int> StockID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    }
}
