//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public int InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
